name: "My action"
description: "Test my actions"

inputs:
  message:
    description: "My message fron origin"
    required: true
    default: "Holis"

runs:
#Nos permite agrupar pasos comunes a reutilizar
  using: "composite"

  steps:
    - name: Hi world
      run: echo "Hola ${{ inputs.message}}"
      #shell es una directiva para que sea exportable y ejecutable
      shell: bash