#Nombre general de yml
name: Hola Mundo

#Indica que el evento push dispara los jobs
#on: [push, pull_request]
on: [push]

#Se indica que ejecutaremos bajo eventos discriminados por rama o criterios elegibles push este caso
#on:
  #push:
    #branches:
      #- master
  #pull_request:
    #branches:
      #- main
jobs:
  #Nombre del job es holita
  holita:
    #Indica el entorno donde se ejecutará
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ls
        uses: ./.github/actions/my-action

      #- name: ls
        #run: ls -al

      #- name: Setup Node.js environment
        #uses: actions/setup-node@v4.0.4

      #- name: node version
        #run: node --version

      #- name: PHP
        #uses: shivammathur/setup-php@v2
        #with:
          #php-version: '8.3'

      #- name: php version
        #run: php --version
            
        #run: |
          #Damos permisos de ejecucion
          #chmod +x script.sh
          #Ejecutamos en cript
          #./script.sh

    #Define los pasos que tendrá el Job, en este casi son 3 pasos 
    #steps:
    #- name: Hola mundo
     # run: echo "Hola Mundillo"

    #- name: touch file
     # run: touch hola.txt

    #- name: Set text
     # run: echo "Hola mundo" >> hola.txt

    #- name: Read file
     # run: cat hola.txt
  #Se define otro  job
 # otherjob:
  #  runs-on: ubuntu-latest
    #Indica que se hará despues que se termine el anterior Job
   # needs: [holita]

    #steps:
    #- name: LS
     # run: ls -al