name: Hola Mundo

on: [push]

jobs:
  holita:
    runs-on: ubuntu-latest

    steps:
    - name: Hola mundo
      run: echo "Hola Mundillo"

    - name: touch file
      run: touch hola.txt

    - name: Set text
      run: echo "Hola mundo" >> hola.txt

    - name: Read file
      run: cat hola.txt

  otherjob:
    runs-on: ubuntu-latest
    needs: [holita]

    steps:
    - name: LS
      run: ls -al